name:                cellGen1D
version:             0.1.0.0
github:              "githubuser/cellGen1D"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cellGen1D#readme>

dependencies:
- base >= 4.7 && < 5
- array
- random
- tasty
- tasty-hunit

library:
  source-dirs: src

executables:
  cellGen1D-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    # https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wmissing-home-modules
    - -Widentities
    - -Wredundant-constraints
    - -Wcpp-undef
    - -Wmissing-export-lists
    dependencies:
    - cellGen1D

tests:
  cellGen1D-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall    
    dependencies:
    - cellGen1D
    - tasty
    - tasty-hunit    
